name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    name: Main Build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Setup msbuild
        uses: actions/setup-dotnet@v4
        
      - name: Install dependencies
        run: dotnet restore "sources/ConsoleTools/ConsoleTools.sln"
        
      - name: Build 
        run: dotnet build --configuration Release --no-restore "sources/ConsoleTools/ConsoleTools.sln"
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal "sources/ConsoleTools/ConsoleTools.sln"
